//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTable
    {
        public RoomTable()
        {
            this.ReservationsTables = new HashSet<ReservationsTable>();
        }
    
        public int RoomID { get; set; }
        public string RoomType { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<ReservationsTable> ReservationsTables { get; set; }
    }
}
